import { describe, it, expect } from 'vitest';
import {
  generateComplianceReport,
  formatReportAsMarkdown,
} from '@/lib/po-dashboard/compliance-report';
import type { CaseloadMember } from '@/lib/po-dashboard/caseload';

const periodStart = new Date('2024-01-01T00:00:00Z');
const periodEnd = new Date('2024-01-31T23:59:59Z');

function makeMember(overrides: Record<string, unknown> = {}): CaseloadMember {
  return {
    id: 'member-1',
    name: 'John Doe',
    riskScore: 3,
    missedCheckIns: 0,
    lastContact: '2024-01-15T00:00:00Z',
    employmentStatus: 'employed',
    housingStatus: 'stable',
    deadlines: [],
    outcomes: [],
    ...overrides,
  } as unknown as CaseloadMember;
}

describe('generateComplianceReport', () => {
  it('returns a valid report for an empty caseload', () => {
    const report = generateComplianceReport([], periodStart, periodEnd);
    expect(report.summary.totalMembers).toBe(0);
    expect(report.summary.compliantCount).toBe(0);
    expect(report.summary.complianceRate).toBe(1);
    expect(report.atRiskMembers).toHaveLength(0);
    expect(report.overdueDeadlines).toHaveLength(0);
    expect(report.positiveOutcomes).toHaveLength(0);
  });

  it('marks a member with high risk score as at-risk', () => {
    const member = makeMember({ id: 'r1', riskScore: 8 });
    const report = generateComplianceReport([member], periodStart, periodEnd);
    expect(report.atRiskMembers).toHaveLength(1);
    expect(report.atRiskMembers[0].riskFactors).toContain('High risk score');
  });

  it('marks a member with missed check-ins as at-risk', () => {
    const member = makeMember({ id: 'r2', missedCheckIns: 3 });
    const report = generateComplianceReport([member], periodStart, periodEnd);
    const factors = report.atRiskMembers[0]?.riskFactors ?? [];
    expect(factors.some((f) => f.includes('missed check-in'))).toBe(true);
  });

  it('detects overdue deadlines within the period', () => {
    const member = makeMember({
      id: 'r3',
      deadlines: [
        {
          type: 'Parole Check-In',
          dueDate: '2024-01-10T00:00:00Z',
          completed: false,
        },
      ],
    });
    const report = generateComplianceReport([member], periodStart, periodEnd);
    expect(report.overdueDeadlines).toHaveLength(1);
    expect(report.overdueDeadlines[0].deadlineType).toBe('Parole Check-In');
    expect(report.overdueDeadlines[0].daysOverdue).toBeGreaterThan(0);
  });

  it('does not flag completed deadlines as overdue', () => {
    const member = makeMember({
      id: 'r4',
      deadlines: [
        {
          type: 'Court Date',
          dueDate: '2024-01-05T00:00:00Z',
          completed: true,
        },
      ],
    });
    const report = generateComplianceReport([member], periodStart, periodEnd);
    expect(report.overdueDeadlines).toHaveLength(0);
  });

  it('captures positive outcomes within the period', () => {
    const member = makeMember({
      id: 'r5',
      outcomes: [
        { description: 'Secured employment', achievedAt: '2024-01-20T00:00:00Z' },
      ],
    });
    const report = generateComplianceReport([member], periodStart, periodEnd);
    expect(report.positiveOutcomes).toHaveLength(1);
    expect(report.positiveOutcomes[0].outcome).toBe('Secured employment');
  });

  it('calculates compliance rate correctly for mixed caseload', () => {
    const compliant = makeMember({ id: 'c1' });
    const atRisk = makeMember({ id: 'c2', riskScore: 9 });
    const report = generateComplianceReport([compliant, atRisk], periodStart, periodEnd);
    expect(report.summary.totalMembers).toBe(2);
    expect(report.summary.complianceRate).toBeCloseTo(0.5);
  });
});

describe('formatReportAsMarkdown', () => {
  it('produces a Markdown string with the summary table', () => {
    const member = makeMember({ id: 'm1', riskScore: 8 });
    const report = generateComplianceReport([member], periodStart, periodEnd);
    const md = formatReportAsMarkdown(report);
    expect(md).toContain('# Parole Officer Compliance Report');
    expect(md).toContain('| Total Members | 1 |');
    expect(md).toContain('## At-Risk Members');
    expect(md).toContain('High risk score');
    expect(md).toContain('_Report generated by REENTRY PO Dashboard_');
  });
});
